MVCAutosAjaxJson/MVCAutosAjaxJson/Models/CarShow.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAutosAjaxJson.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class CarShow
    {
  

        [Required (ErrorMessage ="This Field is Required")]
        public int AutoID { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public Nullable<int> YearMade { get; set; }
        public string Color { get; set; }
        [DisplayName("Image")]
        public string ImagePath { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

        public CarShow()
        {
            ImagePath = "~/Appfiles/Images/image soon.png";
        }

    }

  

}

MVCAutosAjaxJson/MVCAutosAjaxJson/Models/DBModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAutosAjaxJson.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarShow> CarShows { get; set; }
    }
}

MVCAutosAjaxJson/MVCAutosAjaxJson/Models/DBModels.Designer.cs
// T4 code generation is enabled for model 'D:\wor\Finn\MVCAutosAjaxJson\MVCAutosAjaxJson\Models\DBModels.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVCAutosAjaxJson/MVCAutosAjaxJson/Models/DBModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVCAutosAjaxJson/MVCAutosAjaxJson/Controllers/AutoController.cs
using MVCAutosAjaxJson.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCAutosAjaxJson.Controllers
{
    public class AutoController : Controller
    {
        // GET: Auto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAll()
        {
            return View(GetAllAuto());
        }

        IEnumerable<CarShow> GetAllAuto()
        {
            using (DBModel db = new DBModel())
            {
                return db.CarShows.ToList<CarShow>();
            }
        }


        public ActionResult AddOrEdit(int id = 0)
        {
            CarShow zoom = new CarShow();

            return View(zoom);
        }

        [HttpPost]
        public ActionResult AddOrEdit(CarShow c)
        {
            if(c.ImagePath != null )
            {
                string fileName = Path.GetFileNameWithoutExtension(c.ImageUpload.FileName);
                string extension = Path.GetExtension(c.ImageUpload.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                c.ImagePath = "~/Appfiles/Images/" + fileName;
                c.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Appfiles/Images/"), fileName));
            }

            using (DBModel db = new DBModel())
            {
                db.CarShows.Add(c);
                db.SaveChanges();
            }

                return View();
        }

    }
}

MVCAutosAjaxJson/MVCAutosAjaxJson/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Register Auto", "Index", "Auto", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("List Cars", "ViewAll", "Auto")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Big Auto Website</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/JScript.js"></script>
</body>
</html>