MVCRubberShop/MVCRubberShop/Models/Tires.cs
using System;
using System.Collections.Generic;
using static System.Console;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MVCRubberShop.Models
{
    public class Tires
    {

        public int TiresID { get; set; }
        public int TireWidth { get; set; }
        public int Sidewall { get; set; }

        public int RimDiameter { get; set; }
        public int MSRP { get; set; }
        public string Manufacturer { get; set; }


    }


    public class TiresDBContext : DbContext
    {

        public DbSet<Tires> Round { get; set; }

    }




}

MVCRubberShop/MVCRubberShop/Controllers/TiresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MVCRubberShop.Models;

namespace MVCRubberShop.Controllers
{
    public class TiresController : Controller
    {
        private TiresDBContext db = new TiresDBContext();

        // GET: Tires
        public ActionResult Index()
        {
            return View(db.Round.ToList());
        }

        // GET: Tires/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tires tires = db.Round.Find(id);
            if (tires == null)
            {
                return HttpNotFound();
            }
            return View(tires);
        }

        // GET: Tires/Create
        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Front()
        {
            return View();

        }



        // POST: Tires/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TiresID,TireWidth,Sidewall,RimDiameter,MSRP,Manufacturer")] Tires tires)
        {
            if (ModelState.IsValid)
            {
                db.Round.Add(tires);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tires);
        }

        // GET: Tires/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tires tires = db.Round.Find(id);
            if (tires == null)
            {
                return HttpNotFound();
            }
            return View(tires);
        }

        // POST: Tires/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TiresID,TireWidth,Sidewall,RimDiameter,MSRP,Manufacturer")] Tires tires)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tires).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tires);
        }

        // GET: Tires/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tires tires = db.Round.Find(id);
            if (tires == null)
            {
                return HttpNotFound();
            }
            return View(tires);
        }

        // POST: Tires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tires tires = db.Round.Find(id);
            db.Round.Remove(tires);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Show()
        {

            return View(db.Round.ToList());
        }





    }
}

MVCRubberShop/MVCRubberShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MacKenzie Tire Shop Home", "Front", "Tires", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li> @Html.ActionLink("Inventory Page", "Show", "Tires")  </li>

                </ul>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MacKenzie Tires - All Rights Reserved</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

MVCRubberShop/MVCRubberShop/Views/Tires/Create.cshtml
@model MVCRubberShop.Models.Tires

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tires</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TireWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TireWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TireWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sidewall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sidewall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sidewall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RimDiameter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RimDiameter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RimDiameter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MSRP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MSRP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MSRP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVCRubberShop/MVCRubberShop/Views/Tires/Delete.cshtml
@model MVCRubberShop.Models.Tires

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tires</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TireWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TireWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sidewall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sidewall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RimDiameter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RimDiameter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MSRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MSRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVCRubberShop/MVCRubberShop/Views/Tires/Details.cshtml
@model MVCRubberShop.Models.Tires

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Tires</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TireWidth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TireWidth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sidewall)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sidewall)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RimDiameter)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RimDiameter)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MSRP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MSRP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TiresID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVCRubberShop/MVCRubberShop/Views/Tires/Edit.cshtml
@model MVCRubberShop.Models.Tires

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tires</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TiresID)

        <div class="form-group">
            @Html.LabelFor(model => model.TireWidth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TireWidth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TireWidth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sidewall, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sidewall, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sidewall, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RimDiameter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RimDiameter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RimDiameter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MSRP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MSRP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MSRP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

MVCRubberShop/MVCRubberShop/Views/Tires/Front.cshtml
@{
    Layout = null;
}

<!DOCTYPE HTML>

<html>
<head>
    <title>Pro's Only Website</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
    <link rel="stylesheet" href="~/assets/css/mainnnn.css" />
    <!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
    <!--[if lte IE 9]><link rel="stylesheet" href="assets/css/ie9.css" /><![endif]-->
</head>
<body>

    <!-- Header -->
    <div id="header">

        <div class="top">

            <!-- Logo -->
            <div id="logo">

                <h1 id="title">  Generic Tire And Wheel </h1>
                <h3>Used Tire Outlet</h3>
            </div>

            <!-- Nav -->
            <nav id="nav">
                <!--

                    Prologue's nav expects links in one of two formats:

                    1. Hash link (scrolls to a different section within the page)

                       <li><a href="#foobar" id="foobar-link" class="icon fa-whatever-icon-you-want skel-layers-ignoreHref"><span class="label">Foobar</span></a></li>

                    2. Standard link (sends the user to another page/site)

                       <li><a href="http://foobar.tld" id="foobar-link" class="icon fa-whatever-icon-you-want"><span class="label">Foobar</span></a></li>

                -->
                <ul>
                    <li><a href="@Url.Action("Index", "Tires")" id="top-link" class="skel-layers-ignoreHref"><span class="icon fa-home">  Add To Inventory  </span></a></li>
                    <li><a href="@Url.Action("Show", "Tires")" id="portfolio-link" class="skel-layers-ignoreHref"><span class="icon fa-th"> Tires In Stock  </span></a></li>
                    @* <li><a href="@Url.Action("Index", "Start")" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-user">  Nice Page  </span></a></li>
                        <li><a href="@Url.Action("What", "Start")" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-envelope"> What Page </span></a></li>
                        <li><a href="#about" id="about-link" class="skel-layers-ignoreHref"><span class="icon fa-th"> About  </span></a></li>
                        <li><a href="#contact" id="contact-link" class="skel-layers-ignoreHref"><span class="icon fa-user">  Contact Us </span></a></li>*@

                </ul>
            </nav>

        </div>

        <div class="bottom">

            <!-- Social Icons -->
            <ul class="icons">
                <li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
                @*<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>*@
                <li><a href="#" class="icon fa-envelope"><span class="label">Email</span></a></li>
            </ul>

        </div>

    </div>

    <!-- Main -->
    <div id="main">

        <!-- Intro -->
        <section id="top" class="one dark cover">
            <div class="container">

                <header>
                    <h2 class="alt">
                        Welcome to the MacKenzie Tire Emporium.
                        We sell both new and used tires.
                        Our full service garage can take care of all of your
                        vehicle repairs.



                        @*Hi! I'm <strong>Prologue</strong>, a <a href="http://html5up.net/license">free</a> responsive<br />
                        site template designed by <a href="http://www.nba.com"> NBA Website    </a>.*@
                    </h2>
                    <p>
                        Ligula scelerisque justo sem accumsan diam quis<br />
                        vitae natoque dictum sollicitudin elementum.
                    </p>
                </header>

                @*<footer>
                        <a href="#portfolio" class="button scrolly">Magna Aliquam</a>
                        <a href="@Url.Action("What", "Start")" class="button scrolly">Alla Kazam</a>
                        <a href="#portfolio" class="button scrolly">Presto</a>
                    </footer>*@

            </div>
        </section>

        <!-- Portfolio -->
        <!--
        <section id="portfolio" class="two">
            <div class="container">

                <header>
                    <h2>Portfolio</h2>
                </header>

                <p>
                    Vitae natoque dictum etiam semper magnis enim feugiat convallis convallis
                    egestas rhoncus ridiculus in quis risus amet curabitur tempor orci penatibus.
                    Tellus erat mauris ipsum fermentum etiam vivamus eget. Nunc nibh morbi quis
                    fusce hendrerit lacus ridiculus.
                </p>

                <div class="row">
                    <div class="4u 12u$(mobile)">
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic02.jpg" alt="" /></a>
                            <header>
                                <h3>Ipsum Feugiat</h3>
                            </header>
                        </article>
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic03.jpg" alt="" /></a>
                            <header>
                                <h3>Rhoncus Semper</h3>
                            </header>
                        </article>
                    </div>
                    <div class="4u 12u$(mobile)">
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic04.jpg" alt="" /></a>
                            <header>
                                <h3>Magna Nullam</h3>
                            </header>
                        </article>
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic05.jpg" alt="" /></a>
                            <header>
                                <h3>Natoque Vitae</h3>
                            </header>
                        </article>
                    </div>
                    <div class="4u$ 12u$(mobile)">
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic06.jpg" alt="" /></a>
                            <header>
                                <h3>Dolor Penatibus</h3>
                            </header>
                        </article>
                        <article class="item">
                            <a href="#" class="image fit"><img src="images/pic07.jpg" alt="" /></a>
                            <header>
                                <h3>Orci Convallis</h3>
                            </header>
                        </article>
                    </div>
                </div>

            </div>
        </section>

        <!-- About Me -->
        <section id="about" class="three">
            <div class="container">

                @*<header>
                        <h2>About Me</h2>
                    </header>*@

                <footer>
                    <a href="#portfolio" class="button scrolly">Magna Aliquam</a>
                    <a href="@Url.Action("Index", "Tires")" class="button scrolly">Add To Inventory</a>
                    <a href="@Url.Action("Show", "Tires")" class="button scrolly">  Tires In Stock  </a>
                </footer>
                <br />


                <a href="#" class="image featured"><img src="~/images/0tire5.jpg" alt="" /></a>

                <p>
                    Tincidunt eu elit diam magnis pretium accumsan etiam id urna. Ridiculus
                    ultricies curae quis et rhoncus velit. Lobortis elementum aliquet nec vitae
                    laoreet eget cubilia quam non etiam odio tincidunt montes. Elementum sem
                    parturient nulla quam placerat viverra mauris non cum elit tempus ullamcorper
                    dolor. Libero rutrum ut lacinia donec curae mus vel quisque sociis nec
                    ornare iaculis.
                </p>

            </div>
        </section>   

        <!-- Contact -->
        <section id="contact" class="four">
            <div class="container">

                <header>
                    <h2>Contact</h2>
                </header>

                <p>
                    Elementum sem parturient nulla quam placerat viverra
                    mauris non cum elit tempus ullamcorper dolor. Libero rutrum ut lacinia
                    donec curae mus. Eleifend id porttitor ac ultricies lobortis sem nunc
                    orci ridiculus faucibus a consectetur. Porttitor curae mauris urna mi dolor.
                </p>

                <form method="post" action="#">
                    <div class="row">
                        <div class="6u 12u$(mobile)"><input type="text" name="name" placeholder="Name" /></div>
                        <div class="6u$ 12u$(mobile)"><input type="text" name="email" placeholder="Email" /></div>
                        <div class="12u$">
                            <textarea name="message" placeholder="Message"></textarea>
                        </div>
                        <div class="12u$">
                            <input type="submit" value="Send Message" />
                        </div>
                    </div>
                </form>

            </div>
        </section>

    </div>

    <!-- Footer -->
    <div id="footer">

        <!-- Copyright -->
        <ul class="copyright">
            <li>&copy; Big Round Tires. All rights reserved.</li>
            <li>Design: <a href="http://www.google.com"> Google Dude!!</a></li>
        </ul>

    </div>

    <!-- Scripts -->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/jquery.scrolly.min.js"></script>
    <script src="~/assets/js/jquery.scrollzer.min.js"></script>
    <script src="~/assets/js/skel.min.js"></script>
    <script src="~/assets/js/util.js"></script>
    <!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
    <script src="~/assets/js/main.js"></script>

</body>
</html>

MVCRubberShop/MVCRubberShop/Views/Tires/Index.cshtml
@model IEnumerable<MVCRubberShop.Models.Tires>

@{
    ViewBag.Title = "Index";
}

<h2>Add To Inventory Page</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TireWidth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sidewall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RimDiameter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MSRP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TireWidth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sidewall)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RimDiameter)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MSRP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Manufacturer)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.TiresID }) |
            @Html.ActionLink("Details", "Details", new { id=item.TiresID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.TiresID })
        </td>
    </tr>
}

</table>

MVCRubberShop/MVCRubberShop/Views/Tires/Show.cshtml
@model IEnumerable<MVCRubberShop.Models.Tires>

@{
    ViewBag.Title = "Tire Stock List Page";
}

<h2>Tires In Stock</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@




<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TireWidth)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sidewall)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RimDiameter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MSRP)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.NumberInStock)
        </th>*@

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TireWidth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sidewall)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RimDiameter)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSRP)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.NumberInStock)
            </td>*@

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.TiresID }) |
                @Html.ActionLink("Details", "Details", new { id = item.TiresID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.TiresID })
            </td>
        </tr>
    }

</table>